######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 09:03:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloWorld.cpp
