######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 14 16:10:53 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
