	add_square(new square("Go"));
	add_square(new square("Mediterranean Avenue"));
	add_square(new square("Community Chest"));
	add_square(new square("Baltic Avenue"));
	add_square(new square("Income Tax"));
	add_square(new square("Reading Railroad"));
	add_square(new square("Oriental Avenue"));
	add_square(new square("Chance"));
	add_square(new square("Vermont Avenue"));
	add_square(new square("Connecticut Avenue"));
	add_square(new square("Just Visiting"));
	add_square(new square("St. Charles Place"));
	add_square(new square("Electric Company"));
	add_square(new square("States Avenue"));
	add_square(new square("Virginia Avenue"));
	add_square(new square("Pennsylvania Railroad"));
	add_square(new square("St. James Place"));
	add_square(new square("Community Chest"));
	add_square(new square("Tennessee Avenue"));
	add_square(new square("New York Avenue"));
	add_square(new square("Free Parking"));
	add_square(new square("Kentucky Avenue"));
	add_square(new square("Chance"));
	add_square(new square("Indiana Avenue"));
	add_square(new square("Illinois Avenue"));
	add_square(new square("B & O Railroad"));
	add_square(new square("Atlantic Avenue"));
	add_square(new square("Ventnor Avenue"));
	add_square(new square("Water Works"));
	add_square(new square("Marvin Gardens"));
	add_square(new square("Go To Jail"));
	add_square(new square("Pacific Avenue"));
	add_square(new square("North Carolina Avenue"));
	add_square(new square("Community Chest"));
	add_square(new square("Pennsylvania Avenue"));
	add_square(new square("Short Line Railroad"));
	add_square(new square("Chance"));
	add_square(new square("Park Place"));
	add_square(new square("Luxury Tax"));
	add_square(new square("Boardwalk"));
