######################################################################
# Automatically generated by qmake (2.01a) Tue Oct 14 16:32:24 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
