######################################################################
# Automatically generated by qmake (3.0) Wed May 7 12:10:13 2014
######################################################################

TEMPLATE = app
TARGET = lab0
INCLUDEPATH += .
QT += widgets
# Input
SOURCES += helloWorld.cpp
