######################################################################
# Automatically generated by qmake (2.01a) Wed May 21 23:06:58 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += imageviewer.h
SOURCES += imageviewer.cpp main.cpp
