######################################################################
# Automatically generated by qmake (2.01a) Thu May 15 11:24:26 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += lab2.cpp
